repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.259'
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix, --line-length=90]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
    -   id: mypy
        args: [--strict]
        additional_dependencies: [
            pandas_stubs==v1.5.3.230321,
            pandas==1.5.3,
            pytest==7.2.2,
            polars==0.17.11,
            types-setuptools,
            ]
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--line-length=90]
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        files: \.(py|rst|md)$
        args: [--ignore-words-list=ser]
